services:
  app:
    build:
      target: builder  # Use builder stage for test image generation with GD
    environment:
      APPLICATION_ENV: production

  db:
    volumes:
      - ./database/tests:/docker-entrypoint-initdb.d
