<div id="main">
  <h1>
    <?php if (!empty($this->title)): ?>
      <?php echo $this->title ?>
    <?php else: ?>
      Coś chwilowo nie działa, ale nie przejmuj się, to nie Twoja wina! :)
    <?php endif ?>
  </h1>
  <h2><?php echo $this->message ?></h2>

  <?php if (isset($this->exception)): ?>

  <h3>Exception information:</h3>
  <p>
      <b>Message:</b> <?php echo $this->escape($this->exception->getMessage()) ?>
  </p>
  <p>
      <b>Code:</b> <?php echo $this->exception->getCode() ?>
  </p>

  <h3>Stack trace:</h3>
  <pre><?php echo $this->escape($this->exception->getTraceAsString()) ?>
  </pre>

  <h3>Request Parameters:</h3>
  <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
  </pre>
  <?php endif ?>
</div>
