<ul>
  <?php foreach ($this->items as $key => $song): ?>
    <li>
      <?php if (!empty($song->album->thumbnail)): ?>
        <a href="<?php echo $song->getUrl(); ?>">
          <img src="<?php echo $song->album->thumbnail ?>" alt="Okładka albumu <?php echo $song->album->title ?>"
          title="<?php echo $song->title ?>"
          class="thumb" />
        </a>
      <?php endif ?>

      <span><a href="<?php echo $song->getUrl(); ?>"><?php echo $song->title ?></a></span>
      <?php if (!empty($song->artist->items[0])): ?>
        <span><a href="<?php echo $song->artist->items[0]->getUrl(); ?>"><?php echo $song->artist->items[0]->name ?></a></span>
      <?php endif ?>
      <?php if (!empty($song->album->id)): ?>
        <span><a href="<?php echo $song->getAlbumUrl(); ?>"><?php echo $song->album->title ?></a></span>
      <?php endif ?>
      <?php if (!empty($this->showViews) && !empty($song->views)): ?>
        <span class="views"><?php echo number_format($song->views, 0, ',', ' ') ?> wyświetleń</span>
      <?php endif ?>
      <?php if (isset($song->commentCount)): ?>
        <span class="comments"><?php echo $song->commentCount ?> komentarzy</span>
      <?php endif ?>
  <?php endforeach ?>
</ul>
